sonar.projectKey=Kelec_Nextgen
sonar.sources=src
sonar.projectName=Kelec_Nextgen
sonar.projectVersion=1.0

sonar.tests=__tests__
sonar.exclusions=**/node_modules/**,**/__tests__/**,**/android/**,**/ios/**,**/build/**,**/coverage/**,**/scripts/**,**/assets/**,**/misc/**,**src/screen/loggedIn/SettingsTab/DebugZone/*.tsx,**/src/lib/storage/sharedPlatformsData.tsx,**/src/AppErrorBoundary.tsx
sonar.javascript.lcov.reportPaths=./coverage/lcov.info
sonar.testExecutionReportPaths=reports/test-report.xml
sonar.projectVersion=2.6.2